ktor:
    application:
        modules:
            - com.limbus_server.auth.ApplicationKt.module
    deployment:
        port: 8083

database:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://<tu_host_bd>:<tu_puerto_bd>/<tu_base_de_datos_auth> # Reemplaza con tus datos
    user: <tu_usuario_bd> # Reemplaza con tu usuario
    password: <tu_password_bd> # Reemplaza con tu password
    maxPoolSize: 10 # Opcional, tamaño del pool de conexiones